### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by ChrisF999** [Dahlgren/node-steam-workshop#15]
Tried to download both a collection and a file neither downloaded, but files are resolving.

**Comment by Dahlgren** [comment]
Do you have examples of non working items?

**Comment by ChrisF999** [comment]
```js
function Downloadfile(){
    const steamWorkshop = new SteamWorkshop('C:/Users/Khris/Desktop/test');
    steamWorkshop.downloadCollection(966043274, function(err,files){
console.log(files)
    })

}


```
nothing appeared in C:/Users/Khris/Desktop/test

**Comment by ChrisF999** [comment]
I am using the npm version

**Comment by Dahlgren** [comment]
Some of the files lacks the `file_url` property and cannot be downloaded but there's a bug affecting many of the files. I'll make a fix for it.

**Comment by ChrisF999** [comment]
Alright thanks

**Comment by Dahlgren** [comment]
You can test the fix with `npm install https://github.com/Dahlgren/node-steamworkshop/tarball/2476e75099835374eb5b2a6390f679f3e2eb0234`

**Comment by ChrisF999** [comment]
PS C:\Users\Khris\Documents\Git\krakenpublish> npm install https://github.com/Dahlgren/node-steamworkshop/tarball/2476e75099835374eb5b2a6390f679f3e2eb0234
npm ERR! code E404
npm ERR! 404 Not Found - GET https://github.com/Dahlgren/node-steamworkshop/tarball/2476e75099835374eb5b2a6390f679f3e2eb0234
npm ERR! 404 
npm ERR! 404  'https://github.com/Dahlgren/node-steamworkshop/tarball/2476e75099835374eb5b2a6390f679f3e2eb0234' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because 
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404  2. name can no longer contain capital letters
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Khris\AppData\Roaming\npm-cache\_logs\2020-07-17T20_57_44_750Z-debug.log

**Comment by ChrisF999** [comment]
I will npm link it for the time being.

**Comment by ChrisF999** [comment]
C:\Users\Khris\Documents\Git\krakenpublish\node_modules\steam-workshop\src\workshop.js:173
    var fileIds = response.map(function (collection) {
                           ^

TypeError: Cannot read property 'map' of undefined
    at C:\Users\Khris\Documents\Git\krakenpublish\node_modules\steam-workshop\src\workshop.js:173:28


That is what happened.

**Comment by Dahlgren** [comment]
Its a bad error handler for some failing steam responses, I can fix that as well

I tested with your collection above and that worked

**Comment by ChrisF999** [comment]
okay thanks i belive the issue was me not being able to connect to steam since couldfalres dns just had issues ill test again, thanks for the help.

**Comment by ChrisF999** [comment]
yeah it is working thank you, little enhancement request would it be possible to track download progress.

**Comment by ChrisF999** [comment]
After further testing it appears that only handful of files were downloaded.

**Comment by Dahlgren** [comment]
The collection you linked above had 172 files.

63 of those are undefined and can't be downloaded at all from the Steam Workshop Web API. That happens for some games which requires the game to be owned by logged in account which isn't supported by Steam Workshop Web Api.

I end up with 109 files so that matches the number of valid file urls.

**Comment by Dahlgren** [comment]
`0.0.5` released with the fixes
